//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace maqadmin.Datos
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class bdloginEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto bdloginEntities usando la cadena de conexión encontrada en la sección 'bdloginEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public bdloginEntities() : base("name=bdloginEntities", "bdloginEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto bdloginEntities.
        /// </summary>
        public bdloginEntities(string connectionString) : base(connectionString, "bdloginEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto bdloginEntities.
        /// </summary>
        public bdloginEntities(EntityConnection connection) : base(connection, "bdloginEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<tblusuario> tblusuario
        {
            get
            {
                if ((_tblusuario == null))
                {
                    _tblusuario = base.CreateObjectSet<tblusuario>("tblusuario");
                }
                return _tblusuario;
            }
        }
        private ObjectSet<tblusuario> _tblusuario;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<tblprueba> tblprueba
        {
            get
            {
                if ((_tblprueba == null))
                {
                    _tblprueba = base.CreateObjectSet<tblprueba>("tblprueba");
                }
                return _tblprueba;
            }
        }
        private ObjectSet<tblprueba> _tblprueba;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet tblusuario. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTotblusuario(tblusuario tblusuario)
        {
            base.AddObject("tblusuario", tblusuario);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet tblprueba. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTotblprueba(tblprueba tblprueba)
        {
            base.AddObject("tblprueba", tblprueba);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bdloginModel", Name="tblprueba")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblprueba : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto tblprueba.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static tblprueba Createtblprueba(global::System.Int32 id)
        {
            tblprueba tblprueba = new tblprueba();
            tblprueba.id = id;
            return tblprueba;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String prueba
        {
            get
            {
                return _prueba;
            }
            set
            {
                OnpruebaChanging(value);
                ReportPropertyChanging("prueba");
                _prueba = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("prueba");
                OnpruebaChanged();
            }
        }
        private global::System.String _prueba;
        partial void OnpruebaChanging(global::System.String value);
        partial void OnpruebaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bdloginModel", Name="tblusuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblusuario : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto tblusuario.
        /// </summary>
        /// <param name="idusuario">Valor inicial de la propiedad idusuario.</param>
        /// <param name="idlocal">Valor inicial de la propiedad idlocal.</param>
        public static tblusuario Createtblusuario(global::System.Int32 idusuario, global::System.Int32 idlocal)
        {
            tblusuario tblusuario = new tblusuario();
            tblusuario.idusuario = idusuario;
            tblusuario.idlocal = idlocal;
            return tblusuario;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idusuario
        {
            get
            {
                return _idusuario;
            }
            set
            {
                if (_idusuario != value)
                {
                    OnidusuarioChanging(value);
                    ReportPropertyChanging("idusuario");
                    _idusuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idusuario");
                    OnidusuarioChanged();
                }
            }
        }
        private global::System.Int32 _idusuario;
        partial void OnidusuarioChanging(global::System.Int32 value);
        partial void OnidusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                OnusuarioChanging(value);
                ReportPropertyChanging("usuario");
                _usuario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("usuario");
                OnusuarioChanged();
            }
        }
        private global::System.String _usuario;
        partial void OnusuarioChanging(global::System.String value);
        partial void OnusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pass
        {
            get
            {
                return _pass;
            }
            set
            {
                OnpassChanging(value);
                ReportPropertyChanging("pass");
                _pass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pass");
                OnpassChanged();
            }
        }
        private global::System.String _pass;
        partial void OnpassChanging(global::System.String value);
        partial void OnpassChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idlocal
        {
            get
            {
                return _idlocal;
            }
            set
            {
                OnidlocalChanging(value);
                ReportPropertyChanging("idlocal");
                _idlocal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idlocal");
                OnidlocalChanged();
            }
        }
        private global::System.Int32 _idlocal;
        partial void OnidlocalChanging(global::System.Int32 value);
        partial void OnidlocalChanged();

        #endregion

    
    }

    #endregion

    
}
